---
- hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: ansible_os_family == 'Debian'
    - name: Create common config directory
      file:
        path: "{{ common_directory_config }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
  roles:
    - calvinbui.ansible_docker
    - calvinbui.ansible_pip
    - calvinbui.ansible_docker_network
    - calvinbui.ansible_watchtower
    - calvinbui.ansible_traefik
    - calvinbui.ansible_mariadb_docker
    - calvinbui.ansible_nextcloud_docker
    - calvinbui.ansible_onlyoffice_docker
    - calvinbui.ansible_collabora_docker
    - calvinbui.ansible_datadog
  post_tasks:
    - name: Overwrite Nextcloud protocol to HTTPS within config
      command: "docker exec --user www-data {{ nextcloud_name }} php occ config:system:set overwriteprotocol --value='https'"
      register: command_result
      failed_when: "'System config value overwriteprotocol set to string https' not in command_result.stdout"
      changed_when: false
