---

collabora_name: collabora
collabora_image: collabora/code
collabora_ports: []
collabora_environment_variables:
  server_name: "{{ nextcloud_domain }}"
  cert_domain: "{{ nextcloud_domain }}"

collabora_docker_additional_options:
  restart_policy: unless-stopped
  networks: "{{ docker_networks }}"
  capabilities:
    - MKNOD
  labels:
    traefik.protocol: https
