---

collabora_name: collabora
collabora_image: collabora/code
collabora_ports: []
collabora_environment_variables:
  dictionaries: "en_US"
  extra_params: "--o:ssl.enable=false"

collabora_docker_additional_options:
  restart_policy: unless-stopped
  networks: "{{ docker_networks }}"
  capabilities:
    - MKNOD
  labels:
    traefik.protocol: https
