---

collabora_name: collabora
collabora_image: collabora/code
collabora_ports: []
collabora_fqdn: "{{ collabora_name }}.{{ nextcloud_domain }}"
collabora_environment_variables:
  server_name: "{{ collabora_fqdn | regex_replace('\\.', '\\\\.') }}"
  cert_domain: "{{ collabora_fqdn | regex_replace('\\.', '\\\\.') }}"

collabora_docker_additional_options:
  restart_policy: unless-stopped
  networks: "{{ docker_networks }}"
  capabilities:
    - MKNOD
  labels:
    traefik.protocol: https
