---

collabora_name: collabora
collabora_image: collabora/code
collabora_ports:
  - 9980:9980
collabora_logs_directory: "{{ common_directory_config }}/logs"
collabora_certificates_directory: "{{ common_directory_config }}/data"
collabora_environment_variables:
  DONT_GEN_SSL_CERT: "true"
  SSL_VERIFY_CLIENT: "false"

collabora_docker_additional_options:
  restart_policy: unless-stopped
  networks: "{{ docker_networks }}"
