---

collabora_name: collabora
collabora_image: collabora/code
collabora_ports: []
collabora_environment_variables:
  dictionaries: "en_US"
  extra_params: "--o:ssl.termination=true --o:ssl.enable=false"
  domain: "{{ nextcloud_domain | regex_replace('\\.', '\\\\.') }}"

collabora_docker_additional_options:
  restart_policy: unless-stopped
  networks: "{{ docker_networks }}"
  capabilities:
    - MKNOD
  log_options:
    max-size: "10m"
