---
# https://hub.docker.com/r/bilde2910/hauk
hauk_name: hauk
hauk_image: bilde2910/hauk
hauk_config_directory: "{{ common_directory_config }}/{{ hauk_name }}"
hauk_ports:
  - 8081:80
hauk_docker_additional_options:
  restart_policy: unless-stopped

hauk_domain: "hauk.{{ common_tld }}"
hauk_password: $2y$10$9hYQ2LNYkUA2vrNmMkuabOCnZIIxRy/7MDGXuRE31pYnNywsDOsVC
