---

onlyoffice_name: onlyoffice
onlyoffice_image: onlyoffice/documentserver
onlyoffice_ports: []
onlyoffice_environment_variables:
  SSL_VERIFY_CLIENT: "false"

onlyoffice_docker_additional_options:
  restart_policy: unless-stopped
  networks: "{{ docker_networks }}"
  log_options:
    max-size: "10m"
